name: ✨ Feature request
description: 기능 제안
title: "[Feat] "
labels: ["enhancement"]
body:
  - type: textarea
    id: problem
    attributes:
      label: 어떤 문제를 해결하나요?
    validations:
      required: true
  - type: textarea
    id: solution
    attributes:
      label: 제안하는 해결책
      placeholder: "어떤 UI/동작을 기대하나요?"
      validations:
        required: true
